### ISSUE TITLE
NullPointerException when "Share to Gitlab" is used

### ISSUE THREAD

**Issue by hevey** [PavlikPolivka/GitLabProjects#17] opened 2015-12-06 01:51 UTC
This is happening when attempting to create a new project at gitlab.com. Tried to look at it myself but no luck on setting up the Development environment I am afraid

null
java.lang.NullPointerException
	at com.ppolivka.gitlabprojects.api.ApiFacade.getNamespaces(ApiFacade.java:47)
	at com.ppolivka.gitlabprojects.share.GitLabShareDialog$2.run(GitLabShareDialog.java:109)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)

**Comment by oldspiceland** [comment] 2015-12-06 04:16
Same issue.
````
null
java.lang.NullPointerException
	at com.ppolivka.gitlabprojects.api.ApiFacade.getNamespaces(ApiFacade.java:47)
	at com.ppolivka.gitlabprojects.share.GitLabShareDialog$2.run(GitLabShareDialog.java:109)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:563)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:142)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:446)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:392)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:54)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:127)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl$1.run(ProgressManagerImpl.java:126)
	at com.intellij.openapi.application.impl.ApplicationImpl$8.run(ApplicationImpl.java:365)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	at org.jetbrains.ide.PooledThreadExecutor$1$1.run(PooledThreadExecutor.java:55)
````

**Comment by PavlikPolivka** [comment] 2015-12-06 19:27
This is not happening with my GitLab installation
Only when I try to Share on GitLab.com.
I will look into this.

**Comment by oldspiceland** [comment] 2015-12-06 19:33
I've got a fully up to date Gitlab install with no other issues.

George Spiceland

**Comment by PavlikPolivka** [comment] 2015-12-06 19:53
I still cannot reproduce same error. What exavtly is happening?
You have new project. Click on Share on GitLab.
What you see next? Setting window, or dialog with first commit?

**Comment by PavlikPolivka** [comment] 2015-12-06 20:23
I deploy fix for broken Settings Dialog. Can somebody check if its working OK now?

**Comment by oldspiceland** [comment] 2015-12-06 20:28
Specifically my pattern was,
- New Project
- Create Readme
- Share on Gitlab
- API key and URL screen, putting in correct info.
- Error generated and screen comes up with empty groups drop down and initial commit message. No way to push as no way to select a group for the project.

Have not tested new fixes yet.

George Spiceland

**Comment by hevey** [comment] 2015-12-11 11:37
Tested the fix and it looks to have done the job.

**Comment by PavlikPolivka** [comment] 2015-12-11 20:48
Thank you. Closing this issue.

**Closed by PavlikPolivka** 2015-12-11 20:48 UTC
Labels: bug
