### ISSUE TITLE
Remove Source Branch (After Merge) doesn't work

### ISSUE THREAD

**Issue by rippi** [PavlikPolivka/GitLabProjects#78] opened 2017-10-17 11:17 UTC
The checkbox "Remove Source Branch (After Merge)" doesn't work with GitLab Community Edition 8.12.10.
The created Merge Request isn't marked to be deleted after merge.

**Comment by PavlikPolivka** [comment] 2017-12-10 12:44
Works with the newest one (not sure what our current version is). 
This maybe that the 8.12.10 does not support this via REST API.
Closing this as I cannot reproduce this and I will not support older versions.

**Closed by PavlikPolivka** 2017-12-10 12:44 UTC
